# Generated by Django 3.2.9 on 2021-11-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='buplish',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='picture',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
