# Generated by Django 3.2.9 on 2021-11-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20211117_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='update',
        ),
    ]
