# Generated by Django 3.2.9 on 2021-11-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_remove_picture_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='buplish',
            new_name='publish',
        ),
    ]
