# Generated by Django 3.2.9 on 2021-11-12 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='published',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
